import { NodeTemplate, NodeType } from "./NodeType";

export const NODE_TEMPLATES: NodeTemplate[] = [
  {
    nodeType: NodeType.HttpRequest,
    label: "HTTP Request",
    description: "Make HTTP requests to external APIs",
    category: "Network",
    defaultConfig: { url: "", method: "GET", headers: {} },
    inputs: ["body"],
    outputs: ["response"],
  },
  {
    nodeType: NodeType.LLMCall,
    label: "LLM Call",
    description: "Send prompt to a language model",
    category: "AI",
    defaultConfig: { model: "deepseek-chat", prompt: "", temperature: 0.7 },
    inputs: ["context"],
    outputs: ["response"],
  },
  {
    nodeType: NodeType.Condition,
    label: "Condition",
    description: "Branch execution based on condition",
    category: "Flow",
    defaultConfig: { condition: "", operator: "equals" },
    inputs: ["value"],
    outputs: ["true", "false"],
  },
  {
    nodeType: NodeType.Loop,
    label: "Loop",
    description: "Iterate over items",
    category: "Flow",
    defaultConfig: { maxIterations: 10 },
    inputs: ["items"],
    outputs: ["iteration"],
  },
  {
    nodeType: NodeType.Transform,
    label: "Transform",
    description: "Transform data with expressions",
    category: "Data",
    defaultConfig: { expression: "" },
    inputs: ["data"],
    outputs: ["transformed"],
  },
  {
    nodeType: NodeType.Merge,
    label: "Merge",
    description: "Merge multiple data streams",
    category: "Data",
    defaultConfig: { strategy: "object_merge" },
    inputs: ["source_a", "source_b"],
    outputs: ["merged"],
  },
  {
    nodeType: NodeType.Split,
    label: "Split",
    description: "Split array into individual items",
    category: "Data",
    defaultConfig: { field: "items" },
    inputs: ["data"],
    outputs: ["item"],
  },
  {
    nodeType: NodeType.HttpRequest,
    label: "GET Request",
    description: "Simple GET request",
    category: "Network",
    defaultConfig: { url: "", method: "GET", headers: {} },
    inputs: [],
    outputs: ["response"],
  },
  {
    nodeType: NodeType.HttpRequest,
    label: "POST Request",
    description: "POST data to API endpoint",
    category: "Network",
    defaultConfig: { url: "", method: "POST", headers: { "Content-Type": "application/json" } },
    inputs: ["body"],
    outputs: ["response"],
  },
  {
    nodeType: NodeType.LLMCall,
    label: "Chat Completion",
    description: "Standard chat completion call",
    category: "AI",
    defaultConfig: { model: "gpt-4o", prompt: "", temperature: 0.7 },
    inputs: ["context"],
    outputs: ["response"],
  },
  {
    nodeType: NodeType.LLMCall,
    label: "Code Generator",
    description: "Generate code via LLM",
    category: "AI",
    defaultConfig: { model: "deepseek-coder", prompt: "", temperature: 0.2 },
    inputs: ["context"],
    outputs: ["response"],
  },
  {
    nodeType: NodeType.Condition,
    label: "If/Else",
    description: "Standard conditional branch",
    category: "Flow",
    defaultConfig: { condition: "", operator: "equals" },
    inputs: ["value"],
    outputs: ["true", "false"],
  },
  {
    nodeType: NodeType.Condition,
    label: "Contains Check",
    description: "Check if value contains substring",
    category: "Flow",
    defaultConfig: { condition: "", operator: "contains" },
    inputs: ["value"],
    outputs: ["true", "false"],
  },
  {
    nodeType: NodeType.Transform,
    label: "JSON Parse",
    description: "Parse JSON string to object",
    category: "Data",
    defaultConfig: { expression: "json_parse" },
    inputs: ["data"],
    outputs: ["transformed"],
  },
  {
    nodeType: NodeType.Transform,
    label: "Base64 Encode/Decode",
    description: "Encode or decode base64",
    category: "Data",
    defaultConfig: { expression: "base64_encode" },
    inputs: ["data"],
    outputs: ["transformed"],
  },
  {
    nodeType: NodeType.Merge,
    label: "Array Concat",
    description: "Concatenate arrays",
    category: "Data",
    defaultConfig: { strategy: "array_concat" },
    inputs: ["array_a", "array_b"],
    outputs: ["merged"],
  },
  {
    nodeType: NodeType.Loop,
    label: "For Each",
    description: "Loop over array items",
    category: "Flow",
    defaultConfig: { maxIterations: 100 },
    inputs: ["items"],
    outputs: ["iteration"],
  },
  {
    nodeType: NodeType.Split,
    label: "Split Text",
    description: "Split text by delimiter",
    category: "Data",
    defaultConfig: { field: "text", delimiter: "," },
    inputs: ["data"],
    outputs: ["item"],
  },
  {
    nodeType: NodeType.HttpRequest,
    label: "GraphQL Query",
    description: "Execute GraphQL query",
    category: "Network",
    defaultConfig: { url: "", method: "POST", headers: { "Content-Type": "application/json" }, query: "" },
    inputs: ["variables"],
    outputs: ["response"],
  },
  {
    nodeType: NodeType.LLMCall,
    label: "Embedding",
    description: "Generate text embeddings",
    category: "AI",
    defaultConfig: { model: "voyage-2", input: "", task: "embedding" },
    inputs: ["text"],
    outputs: ["embedding"],
  },
];

export function getTemplate(label: string): NodeTemplate | undefined {
  return NODE_TEMPLATES.find((t) => t.label === label);
}

export function getTemplatesByCategory(category: string): NodeTemplate[] {
  return NODE_TEMPLATES.filter((t) => t.category === category);
}
