//! Node registry and template catalog: all available node templates organized by category.

use super::types::{NodeTemplate, NodeType};

pub struct NodeRegistry;

impl NodeRegistry {
    pub fn all_templates() -> Vec<NodeTemplate> {
        vec![
            NodeTemplate {
                node_type: NodeType::HttpRequest,
                label: "HTTP Request",
                description: "Make HTTP requests to external APIs",
                category: "Network",
                default_config: serde_json::json!({"url": "", "method": "GET", "headers": {}}),
                inputs: vec!["body"],
                outputs: vec!["response"],
            },
            NodeTemplate {
                node_type: NodeType::LLMCall,
                label: "LLM Call",
                description: "Send prompt to a language model",
                category: "AI",
                default_config: serde_json::json!({"model": "deepseek-chat", "prompt": "", "temperature": 0.7}),
                inputs: vec!["context"],
                outputs: vec!["response"],
            },
            NodeTemplate {
                node_type: NodeType::Condition,
                label: "Condition",
                description: "Branch execution based on condition",
                category: "Flow",
                default_config: serde_json::json!({"condition": "", "operator": "equals"}),
                inputs: vec!["value"],
                outputs: vec!["true", "false"],
            },
            NodeTemplate {
                node_type: NodeType::Loop,
                label: "Loop",
                description: "Iterate over items",
                category: "Flow",
                default_config: serde_json::json!({"max_iterations": 10}),
                inputs: vec!["items"],
                outputs: vec!["iteration"],
            },
            NodeTemplate {
                node_type: NodeType::Transform,
                label: "Transform",
                description: "Transform data with expressions",
                category: "Data",
                default_config: serde_json::json!({"expression": ""}),
                inputs: vec!["data"],
                outputs: vec!["transformed"],
            },
            NodeTemplate {
                node_type: NodeType::Merge,
                label: "Merge",
                description: "Merge multiple data streams",
                category: "Data",
                default_config: serde_json::json!({"strategy": "object_merge"}),
                inputs: vec!["source_a", "source_b"],
                outputs: vec!["merged"],
            },
            NodeTemplate {
                node_type: NodeType::Split,
                label: "Split",
                description: "Split array into individual items",
                category: "Data",
                default_config: serde_json::json!({"field": "items"}),
                inputs: vec!["data"],
                outputs: vec!["item"],
            },
            NodeTemplate {
                node_type: NodeType::HttpRequest,
                label: "GET Request",
                description: "Simple GET request",
                category: "Network",
                default_config: serde_json::json!({"url": "", "method": "GET", "headers": {}}),
                inputs: vec![],
                outputs: vec!["response"],
            },
            NodeTemplate {
                node_type: NodeType::HttpRequest,
                label: "POST Request",
                description: "POST data to API endpoint",
                category: "Network",
                default_config: serde_json::json!({"url": "", "method": "POST", "headers": {"Content-Type": "application/json"}}),
                inputs: vec!["body"],
                outputs: vec!["response"],
            },
            NodeTemplate {
                node_type: NodeType::LLMCall,
                label: "Chat Completion",
                description: "Standard chat completion call",
                category: "AI",
                default_config: serde_json::json!({"model": "gpt-4o", "prompt": "", "temperature": 0.7}),
                inputs: vec!["context"],
                outputs: vec!["response"],
            },
            NodeTemplate {
                node_type: NodeType::LLMCall,
                label: "Code Generator",
                description: "Generate code via LLM",
                category: "AI",
                default_config: serde_json::json!({"model": "deepseek-coder", "prompt": "", "temperature": 0.2}),
                inputs: vec!["context"],
                outputs: vec!["response"],
            },
            NodeTemplate {
                node_type: NodeType::Condition,
                label: "If/Else",
                description: "Standard conditional branch",
                category: "Flow",
                default_config: serde_json::json!({"condition": "", "operator": "equals"}),
                inputs: vec!["value"],
                outputs: vec!["true", "false"],
            },
            NodeTemplate {
                node_type: NodeType::Condition,
                label: "Contains Check",
                description: "Check if value contains substring",
                category: "Flow",
                default_config: serde_json::json!({"condition": "", "operator": "contains"}),
                inputs: vec!["value"],
                outputs: vec!["true", "false"],
            },
            NodeTemplate {
                node_type: NodeType::Transform,
                label: "JSON Parse",
                description: "Parse JSON string to object",
                category: "Data",
                default_config: serde_json::json!({"expression": "json_parse"}),
                inputs: vec!["data"],
                outputs: vec!["transformed"],
            },
            NodeTemplate {
                node_type: NodeType::Transform,
                label: "Base64 Encode/Decode",
                description: "Encode or decode base64",
                category: "Data",
                default_config: serde_json::json!({"expression": "base64_encode"}),
                inputs: vec!["data"],
                outputs: vec!["transformed"],
            },
            NodeTemplate {
                node_type: NodeType::Merge,
                label: "Array Concat",
                description: "Concatenate arrays",
                category: "Data",
                default_config: serde_json::json!({"strategy": "array_concat"}),
                inputs: vec!["array_a", "array_b"],
                outputs: vec!["merged"],
            },
            NodeTemplate {
                node_type: NodeType::Loop,
                label: "For Each",
                description: "Loop over array items",
                category: "Flow",
                default_config: serde_json::json!({"max_iterations": 100}),
                inputs: vec!["items"],
                outputs: vec!["iteration"],
            },
            NodeTemplate {
                node_type: NodeType::Split,
                label: "Split Text",
                description: "Split text by delimiter",
                category: "Data",
                default_config: serde_json::json!({"field": "text", "delimiter": ","}),
                inputs: vec!["data"],
                outputs: vec!["item"],
            },
            NodeTemplate {
                node_type: NodeType::HttpRequest,
                label: "GraphQL Query",
                description: "Execute GraphQL query",
                category: "Network",
                default_config: serde_json::json!({"url": "", "method": "POST", "headers": {"Content-Type": "application/json"}, "query": ""}),
                inputs: vec!["variables"],
                outputs: vec!["response"],
            },
            NodeTemplate {
                node_type: NodeType::LLMCall,
                label: "Embedding",
                description: "Generate text embeddings",
                category: "AI",
                default_config: serde_json::json!({"model": "voyage-2", "input": "", "task": "embedding"}),
                inputs: vec!["text"],
                outputs: vec!["embedding"],
            },
            NodeTemplate {
                node_type: NodeType::Code,
                label: "Python Execute",
                description: "Sandboxed Python code execution",
                category: "Flow",
                default_config: serde_json::json!({"code": "", "timeout": 30, "sandbox": true}),
                inputs: vec!["input"],
                outputs: vec!["result", "error"],
            },
            NodeTemplate {
                node_type: NodeType::Code,
                label: "JS Execute",
                description: "Sandboxed JavaScript execution",
                category: "Flow",
                default_config: serde_json::json!({"code": "", "timeout": 30, "sandbox": true}),
                inputs: vec!["input"],
                outputs: vec!["result", "error"],
            },
            NodeTemplate {
                node_type: NodeType::Trigger,
                label: "Cron Trigger",
                description: "Scheduled execution via cron expression",
                category: "Flow",
                default_config: serde_json::json!({"cron": "0 * * * *", "timezone": "UTC"}),
                inputs: vec![],
                outputs: vec!["trigger"],
            },
            NodeTemplate {
                node_type: NodeType::Trigger,
                label: "Webhook",
                description: "HTTP webhook trigger",
                category: "Flow",
                default_config: serde_json::json!({"method": "POST", "path": "/webhook"}),
                inputs: vec![],
                outputs: vec!["payload"],
            },
            NodeTemplate {
                node_type: NodeType::Trigger,
                label: "Manual Trigger",
                description: "Manual button-press trigger",
                category: "Flow",
                default_config: serde_json::json!({}),
                inputs: vec![],
                outputs: vec!["start"],
            },
            NodeTemplate {
                node_type: NodeType::Wait,
                label: "Timer Wait",
                description: "Pause execution for a fixed duration",
                category: "Flow",
                default_config: serde_json::json!({"duration_secs": 10}),
                inputs: vec!["input"],
                outputs: vec!["output"],
            },
            NodeTemplate {
                node_type: NodeType::Wait,
                label: "Condition Wait",
                description: "Pause until a condition is met",
                category: "Flow",
                default_config: serde_json::json!({"condition": "", "poll_interval_secs": 5, "timeout_secs": 300}),
                inputs: vec!["input"],
                outputs: vec!["output", "timeout"],
            },
            NodeTemplate {
                node_type: NodeType::Switch,
                label: "Switch Case",
                description: "Multi-route switch-case routing",
                category: "Flow",
                default_config: serde_json::json!({"cases": [], "default": "default"}),
                inputs: vec!["value"],
                outputs: vec!["case_0", "case_1", "default"],
            },
            NodeTemplate {
                node_type: NodeType::Merge,
                label: "Parallel Merge",
                description: "Aggregate results from parallel branches",
                category: "Data",
                default_config: serde_json::json!({"strategy": "all", "timeout_secs": 60}),
                inputs: vec!["branch_a", "branch_b"],
                outputs: vec!["merged"],
            },
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_registry_has_templates() {
        let templates = NodeRegistry::all_templates();
        assert!(!templates.is_empty());
    }
}
