[package]
name = "morn-harness"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
morn-kernel = { workspace = true }
morn-capability = { workspace = true }
morn-work = { workspace = true }
morn-actor = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }


[dev-dependencies]
morn-world = { workspace = true }
serde_json = { workspace = true }
