//! channel — Exposes communication channels for users and external platforms.
pub mod adapter;
#[cfg(feature = "channels-full")]
pub mod browser_ext;
pub mod cli;
pub mod desktop;
#[cfg(feature = "channels-full")]
pub mod dingtalk;
#[cfg(feature = "channels-full")]
pub mod feishu;
#[cfg(feature = "channels-full")]
pub mod miniprogram;
#[cfg(feature = "channels-full")]
pub mod pushplus;
#[cfg(feature = "channels-full")]
pub mod qqbot;
pub mod rest_api;
#[cfg(feature = "channels-full")]
pub mod serverchan;
#[cfg(feature = "channels-full")]
pub mod smtp;
#[cfg(feature = "channels-full")]
pub mod telegram;
#[cfg(feature = "channels-full")]
pub mod webhook;
#[cfg(feature = "channels-full")]
pub mod wechat_mp;
#[cfg(feature = "channels-full")]
pub mod wecom;
